### PR TITLE
Ft page design #160486296

### PR DESCRIPTION
**Pull request by patrickf949**
@pbkabali @medihamad @codephilip @Sekams @joegeoffrey please review

### CODE REVIEW

**Comment by patrickf949** [comment]
Page Design complete

**Comment by pbkabali** [comment]
nice work. cant seem to see a sign-out option thou. plus check heading "your to-do lists" on page home.html

**Comment by patrickf949** [comment]
> nice work. cant seem to see a sign-out option thou. plus check heading "your to-do lists" on page home.html

Will work on em

**Comment by patrickf949** [comment]
@joegeoffrey neat interface, can't seem access other pages tho

**Pull request merged**
